# Đặt tên cho workflow
name: Build, Push, and Deploy Docker Images

# Trigger: Chạy workflow này mỗi khi có push lên nhánh 'main'
on:
  push:
    branches: ["main"]

# Định nghĩa các công việc cần làm
jobs:
  build_push_and_deploy:
    # Chạy trên một máy ảo Ubuntu mới nhất
    runs-on: ubuntu-latest

    # Các bước thực hiện
    steps:
      # Bước 1: Lấy code từ repository về máy ảo
      - name: Check out the repo
        uses: actions/checkout@v3

      # Bước 2: Đăng nhập vào Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Bước 3: Build và push image cho Backend
      - name: Build and push Backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:latest

      # Bước 4: Build và push image cho Frontend
      - name: Build and push Frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:latest

      # BƯỚC 5 (MỚI): Trigger deploy cho Backend trên Render
      - name: Trigger Render Backend Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}

      # BƯỚC 6 (MỚI): Trigger deploy cho Frontend trên Render
      - name: Trigger Render Frontend Deploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}
